### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "MyNewPatient",
  "email": "MyNewPatient@gmail.com",
  "address": "address of MyNewPatient",
  "dateOfBirth": "2000-01-01",
  "registeredDate": "2025-01-01"
}
###